// <auto-generated />
namespace nguyentanhung_2011780577_BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class taodulieubang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taodulieubang));
        
        string IMigrationMetadata.Id
        {
            get { return "202303100206347_tao du lieu bang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
